[package]
name = "athena-tu-darmstadt-exercise"
version = "0.1.0"
entrypoint = "templates/lib.typ"
authors = ["JeyRunner <https://github.com/JeyRunner>"]
license = "MIT"
description = "Exercise template for TU Darmstadt (Technische Universität Darmstadt)."
repository = "https://github.com/JeyRunner/tuda-typst-templates"
keywords = ["TU Darmstadt", "Technische Universität Darmstadt", "Exercise"]
categories = ["thesis"]
exclude = ["tests", "example_tudapub.pdf", "example_tudapub.typ"]

[template]
path = "templates_examples/tudaexercise"
entrypoint = "main.typ"
thumbnail = "img/tudaexercise_prev-01.png"
